### ISSUE TITLE
question

### ISSUE THREAD

**Issue by K1-aus** [mnswdhw/DefenseGAN-and-Cowboy-Defense#1]
Hi, can you share the defense result with me? such as pictures

**Comment by mnswdhw** [comment]
Hello @K1-aus , I currently do not have the reconstructed images. However, I do have the experimental metrics I had measured earlier.

For defense-gan : 
Clean batch0 Accuracy: 86
Adversarial batch0 Accuracy: 82

For cowboy defense: 
Clean batch0 Accuracy: 86
Adversarial batch0 Accuracy: 82

learning rate (lr): 10 
rec_iter: 200
rec_rr: 10 
model used: A

The images can be obtained very easily by running the code defense.py. It will open a tensorboard session which will log all the images and the metrics if any.
